package es.caib.dir3caib.ws.dir3.unidad.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Mon Nov 08 13:12:06 CET 2021
 * Generated source version: 2.2.12-patch-04
 * 
 */
 
@WebService(targetNamespace = "http://impl.manager.directorio.map.es", name = "SD01UN_DescargaUnidades")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SD01UNDescargaUnidades {

    @WebResult(name = "exportarReturn", targetNamespace = "http://impl.manager.directorio.map.es", partName = "exportarReturn")
    @WebMethod
    public RespuestaWS exportar(
        @WebParam(partName = "unidadesRequest", name = "unidadesRequest")
        UnidadesWs unidadesRequest
    );

    @WebResult(name = "exportarReturn", targetNamespace = "http://impl.manager.directorio.map.es", partName = "exportarReturn")
    @WebMethod
    public RespuestaWS exportarV2(
        @WebParam(partName = "unidadesRequest", name = "unidadesRequest")
        UnidadesWs unidadesRequest
    );

    @WebResult(name = "exportarReturn", targetNamespace = "http://impl.manager.directorio.map.es", partName = "exportarReturn")
    @WebMethod
    public RespuestaWS exportarV3(
        @WebParam(partName = "unidadesRequest", name = "unidadesRequest")
        UnidadesWsVersion unidadesRequest
    );
}
