
/*
 * 
 */

package es.caib.dir3caib.ws.dir3.catalogo.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Mon Sep 15 12:29:06 CEST 2014
 * Generated source version: 2.2.12-patch-04
 * 
 */


@WebServiceClient(name = "SC21CT_VolcadoCatalogosService", 
                  wsdlLocation = "http://pre-dir3ws.redsara.es/directorio/services/SC21CT_VolcadoCatalogos?wsdl",
                  targetNamespace = "http://impl.manager.directorio.map.es") 
public class SC21CTVolcadoCatalogosService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.manager.directorio.map.es", "SC21CT_VolcadoCatalogosService");
    public final static QName SC21CTVolcadoCatalogos = new QName("http://impl.manager.directorio.map.es", "SC21CT_VolcadoCatalogos");
    static {
        URL url = null;
        try {
            url = new URL("http://pre-dir3ws.redsara.es/directorio/services/SC21CT_VolcadoCatalogos?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://pre-dir3ws.redsara.es/directorio/services/SC21CT_VolcadoCatalogos?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SC21CTVolcadoCatalogosService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SC21CTVolcadoCatalogosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SC21CTVolcadoCatalogosService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns SC21CTVolcadoCatalogos
     */
    @WebEndpoint(name = "SC21CT_VolcadoCatalogos")
    public SC21CTVolcadoCatalogos getSC21CTVolcadoCatalogos() {
        return super.getPort(SC21CTVolcadoCatalogos, SC21CTVolcadoCatalogos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SC21CTVolcadoCatalogos
     */
    @WebEndpoint(name = "SC21CT_VolcadoCatalogos")
    public SC21CTVolcadoCatalogos getSC21CTVolcadoCatalogos(WebServiceFeature... features) {
        return super.getPort(SC21CTVolcadoCatalogos, SC21CTVolcadoCatalogos.class, features);
    }

}
