package es.caib.dir3caib.ws.dir3.catalogo.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Mon Nov 08 13:11:37 CET 2021
 * Generated source version: 2.2.12-patch-04
 * 
 */
 
@WebService(targetNamespace = "http://impl.manager.directorio.map.es", name = "SC21CT_VolcadoCatalogos")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SC21CTVolcadoCatalogos {

    @WebResult(name = "exportarReturn", targetNamespace = "http://impl.manager.directorio.map.es", partName = "exportarReturn")
    @WebMethod
    public RespuestaWS exportar(
        @WebParam(partName = "login", name = "login")
        java.lang.String login,
        @WebParam(partName = "password", name = "password")
        java.lang.String password,
        @WebParam(partName = "formatoFichero", name = "formatoFichero")
        java.lang.String formatoFichero,
        @WebParam(partName = "catalogo", name = "catalogo")
        java.lang.String catalogo
    );

    @WebResult(name = "exportarReturn", targetNamespace = "http://impl.manager.directorio.map.es", partName = "exportarReturn")
    @WebMethod
    public RespuestaWS exportarV2(
        @WebParam(partName = "login", name = "login")
        java.lang.String login,
        @WebParam(partName = "password", name = "password")
        java.lang.String password,
        @WebParam(partName = "formatoFichero", name = "formatoFichero")
        java.lang.String formatoFichero,
        @WebParam(partName = "catalogo", name = "catalogo")
        java.lang.String catalogo
    );
}
