
-- Hibernate/JPA no proporciona cap mecanisme per crear Indexos 
-- sobre taules @JoinTable. Els següents indexos són sobre aquest tipus de taula

-- Tabla DIR_SERVICIOOFI

CREATE INDEX DIR_OFI_SERV_FK_I
ON DIR_SERVICIOOFI(CODSERVICIO);

CREATE INDEX DIR_SER_OFI_FK_I
ON DIR_SERVICIOOFI(CODOFICINA);


-- Tabla DIR_HISTORICOUO

CREATE INDEX DIR_UNI_UNI_HISTANTE_FK_I
ON DIR_HISTORICOUO(CODANTERIOR);

CREATE INDEX DIR_UNI_UNI_HISTULTI_FK_I
ON DIR_HISTORICOUO(CODULTIMA);


-- Tabla DIR_HISTORICOOFI

CREATE INDEX DIR_OFI_OFI_HISTANTE_FK_I
ON DIR_HISTORICOOFI(CODANTERIOR);

CREATE INDEX DIR_OFI_OFI_HISTULTI_FK_I
ON DIR_HISTORICOOFI(CODULTIMA);