

--16/03/2015  Descarga fechas pasadas a Date.

alter table DIR_DESCARGA ADD FECHAINICIO2 TIMESTAMP(6);
alter table DIR_DESCARGA ADD FECHAFIN2 TIMESTAMP(6);
alter table DIR_DESCARGA ADD FECHAIMPORTACION2 TIMESTAMP(6);


UPDATE DIR_DESCARGA SET FECHAINICIO2 = TO_DATE(FECHAINICIO, 'dd/mm/yyyy') where FECHAINICIO is not null ;
UPDATE DIR_DESCARGA SET FECHAFIN2 = TO_DATE(FECHAFIN, 'dd/mm/yyyy') where FECHAFIN is not null;
UPDATE DIR_DESCARGA SET FECHAIMPORTACION2 = TO_DATE(FECHAIMPORTACION, 'dd/mm/yyyy') where FECHAIMPORTACION is not null;

alter table DIR_DESCARGA DROP COLUMN FECHAINICIO;
alter table DIR_DESCARGA DROP COLUMN FECHAFIN;
alter table DIR_DESCARGA DROP COLUMN FECHAIMPORTACION;

alter table DIR_DESCARGA RENAME COLUMN FECHAINICIO2 to FECHAINICIO;
alter table DIR_DESCARGA RENAME COLUMN FECHAFIN2 to FECHAFIN;
alter table DIR_DESCARGA RENAME COLUMN FECHAIMPORTACION2 to FECHAIMPORTACION;


-- 26/03/2015 Index amb nom incorrecte

drop index RWE_CATPROVINCIA_PK_I;
create index DIR_CATPROVINCIA_PK_I on DIR_CATPROVINCIA (CODIGOPROVINCIA);



