-- Tabla DIR_CATAMBITOTERRITORIAL

DROP INDEX DIR_CATAMBTERR_CATNIVADM_FK_I;


-- Tabla DIR_CATCOMUNIDADAUTONOMA

DROP INDEX DIR_CATCOMUNAUT_CATPAIS_FK_I;


-- Tabla DIR_CATLOCALIDAD

DROP INDEX DIR_CATLOCAL_CATPROVIN_FK_I;


DROP INDEX DIR_CATLOCAL_CATENTGEOGR_FK_I;


-- Tabla DIR_CATPROVINCIA

DROP INDEX DIR_CATPROV_CATCOMUNAUT_FK_I;


-- Tabla DIR_CONTACTOOFI

DROP INDEX DIR_CONTOFI_CATTIPCONT_FK_I;


DROP INDEX DIR_OFICINA_CONTACTOSOFI_FK_I;


-- Tabla DIR_CONTACTOUO

DROP INDEX DIR_CONTACUO_CATTIPOCONT_FK_I;


DROP INDEX DIR_UNIDAD_CONTACTOSUO_FK_I;


-- Tabla DIR_HISTORICOOFI

DROP INDEX DIR_OFI_OFI_HISTANTE_FK_I;


DROP INDEX DIR_OFI_OFI_HISTULTI_FK_I;


-- Tabla DIR_HISTORICOUO

DROP INDEX DIR_UNI_UNI_HISTANTE_FK_I;


DROP INDEX DIR_UNI_UNI_HISTULTI_FK_I;


-- Tabla DIR_OFICINA

DROP INDEX DIR_OFICINA_CATTIPOVIA_FK_I;


DROP INDEX DIR_OFICINA_CATPAIS_FK_I;


DROP INDEX DIR_OFICINA_OFICINA_FK_I;


DROP INDEX DIR_OFICINA_CATJERAROFI_FK_I;


DROP INDEX DIR_OFICINA_CATCOMUNIAUT_FK_I;


DROP INDEX DIR_OFICINA_CATNIVELADMIN_FK_I;


DROP INDEX DIR_OFICINA_CATESTADENTI_FK_I;


DROP INDEX DIR_OFICINA_CATLOCAL_FK_I;


DROP INDEX DIR_OFICINA_UNIDAD_FK_I;


-- Tabla DIR_RELACIONORGANIZATIVAOFI

DROP INDEX DIR_RELORGANOFI_CATESTENT_FK_I;


DROP INDEX DIR_UNIDAD_RELORGOFI_FK_I;


DROP INDEX DIR_OFICINA_RELORGOFI_FK_I;


-- Tabla DIR_RELACIONSIROFI

DROP INDEX DIR_RELSIROFI_CATESTENTI_FK_I;


DROP INDEX DIR_UNIDAD_RELSIROFI_FK_I;


DROP INDEX DIR_OFICINA_RELSIROFI_FK_I;


-- Tabla DIR_SERVICIOOFI

DROP INDEX DIR_OFI_SERV_FK_I;


DROP INDEX DIR_SER_OFI_FK_I;


-- Tabla DIR_UNIDAD

DROP INDEX DIR_UNIDAD_CATPROVINCIA_FK_I;


DROP INDEX DIR_UNIDAD_UNIDADRAIZ_FK_I;


DROP INDEX DIR_UNIDAD_CATAMBCOMAUTO_FK_I;


DROP INDEX DIR_UNIDAD_CATCOMUNIAUTO_FK_I;


DROP INDEX DIR_UNIDAD_UNIDADSUPERIOR_FK_I;


DROP INDEX DIR_UNIDAD_CATTIPOVIA_FK_I;


DROP INDEX DIR_UNIDAD_CATPAIS_FK_I;


DROP INDEX DIR_UNIDAD_CATENTGEOGRAF_FK_I;


DROP INDEX DIR_UNIDAD_CATAMBPAIS_FK_I;


DROP INDEX DIR_UNIDAD_CATTIPENTPUBL_FK_I;


DROP INDEX DIR_UNIDAD_MUNICIPIO_FK_I;


DROP INDEX DIR_UNIDAD_CATISLA_FK_I;


DROP INDEX DIR_UNIDAD_CATTIPUNIORG_FK_I;


DROP INDEX DIR_UNIDAD_CATNIVELADMIN_FK_I;


DROP INDEX DIR_UNIDAD_CATESTENTIDAD_FK_I;


DROP INDEX DIR_UNIDAD_CATAMBITTERR_FK_I;


DROP INDEX DIR_UNIDAD_CATLOCAL_FK_I;


DROP INDEX DIR_UNIDAD_UNIDADEDPPRINC_FK_I;
