--USUARIOS
INSERT INTO SC_WL_USUARI (USU_CODI,USU_PASS,USU_NOM) VALUES ('dir3caib','dir3caib','Administrador');

--USUARIOS-GRUPOS
INSERT INTO SC_WL_USUGRU (UGR_CODUSU,UGR_CODGRU) VALUES ('dir3caib','DIR_ADMIN');
