
/*
 * 
 */

package es.caib.dir3caib.ws.dir3.oficina.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Mon Sep 15 12:29:10 CEST 2014
 * Generated source version: 2.2.12-patch-04
 * 
 */


@WebServiceClient(name = "SD02OF_DescargaOficinasService", 
                  wsdlLocation = "http://pre-dir3ws.redsara.es/directorio/services/SD02OF_DescargaOficinas?wsdl",
                  targetNamespace = "http://impl.manager.directorio.map.es") 
public class SD02OFDescargaOficinasService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.manager.directorio.map.es", "SD02OF_DescargaOficinasService");
    public final static QName SD02OFDescargaOficinas = new QName("http://impl.manager.directorio.map.es", "SD02OF_DescargaOficinas");
    static {
        URL url = null;
        try {
            url = new URL("http://pre-dir3ws.redsara.es/directorio/services/SD02OF_DescargaOficinas?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://pre-dir3ws.redsara.es/directorio/services/SD02OF_DescargaOficinas?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SD02OFDescargaOficinasService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SD02OFDescargaOficinasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SD02OFDescargaOficinasService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns SD02OFDescargaOficinas
     */
    @WebEndpoint(name = "SD02OF_DescargaOficinas")
    public SD02OFDescargaOficinas getSD02OFDescargaOficinas() {
        return super.getPort(SD02OFDescargaOficinas, SD02OFDescargaOficinas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SD02OFDescargaOficinas
     */
    @WebEndpoint(name = "SD02OF_DescargaOficinas")
    public SD02OFDescargaOficinas getSD02OFDescargaOficinas(WebServiceFeature... features) {
        return super.getPort(SD02OFDescargaOficinas, SD02OFDescargaOficinas.class, features);
    }

}
