
/*
 * 
 */

package es.caib.dir3caib.ws.api.catalogo;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Mon Mar 16 13:20:04 CET 2015
 * Generated source version: 2.2.12-patch-04
 * 
 */


@WebServiceClient(name = "Dir3CaibObtenerCatalogosWsService", 
                  wsdlLocation = "http://localhost:8080/dir3caib/ws/Dir3CaibObtenerCatalogos?wsdl",
                  targetNamespace = "http://www.caib.es/dir3caib") 
public class Dir3CaibObtenerCatalogosWsService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.caib.es/dir3caib", "Dir3CaibObtenerCatalogosWsService");
    public final static QName Dir3CaibObtenerCatalogosWs = new QName("http://www.caib.es/dir3caib", "Dir3CaibObtenerCatalogosWs");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/dir3caib/ws/Dir3CaibObtenerCatalogos?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/dir3caib/ws/Dir3CaibObtenerCatalogos?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Dir3CaibObtenerCatalogosWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Dir3CaibObtenerCatalogosWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Dir3CaibObtenerCatalogosWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns Dir3CaibObtenerCatalogosWs
     */
    @WebEndpoint(name = "Dir3CaibObtenerCatalogosWs")
    public Dir3CaibObtenerCatalogosWs getDir3CaibObtenerCatalogosWs() {
        return super.getPort(Dir3CaibObtenerCatalogosWs, Dir3CaibObtenerCatalogosWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Dir3CaibObtenerCatalogosWs
     */
    @WebEndpoint(name = "Dir3CaibObtenerCatalogosWs")
    public Dir3CaibObtenerCatalogosWs getDir3CaibObtenerCatalogosWs(WebServiceFeature... features) {
        return super.getPort(Dir3CaibObtenerCatalogosWs, Dir3CaibObtenerCatalogosWs.class, features);
    }

}
